name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build-Server-Jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'
      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=false -Pdevelop -B --file easydata/pom.xml
