name: "Build"
on:
  workflow_dispatch: ~
  push:
    paths:
      - "**.java"
    branches:
      - "stable"
      - "development"
  pull_request:
    paths:
      - "**.java"
    types:
      - opened
      - synchronize
      - reopened
jobs:
  Build-Server-Jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'
      - name: Build with Maven
        run: ./mvnw clean package -Dmaven.test.skip=false -Pdevelop -B
